name: gym_kid
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  delayed_display: ^2.0.0
  easy_date_timeline: ^0.1.1
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_timeline_calendar: ^1.0.9
  get: ^4.6.5
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.3+1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.1
  sizer: ^2.0.15
  zoom_tap_animation: ^1.1.0
  numberpicker: ^2.1.2
  flutter_animation_progress_bar: ^2.3.1
  countup: ^0.1.4
  motion: ^1.4.0
  syncfusion_flutter_gauges: ^23.1.44
  page_flip: ^0.2.3
  image_gradient: ^0.0.2
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.44
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  lottie: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

  cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.jpg" # Path to your main icon
  adaptive_icon_foreground: "assets/images/icon_app.jpg" # Adaptive icon for Android
  adaptive_icon_background: "#000000" # Background color for adaptive icon
  remove_alpha_channel_ios: true # Remove alpha channel on iOS icons (optional)


  # The "flutter_lints" package below contains a set of recommended lints to

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/animations/
  - assets/images/
  - assets/icons/
  - assets/app_images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppins-medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
